name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17'

    - name: Install infisical-cli
      shell: bash
      run: curl -1sLf  'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash

    - name: apt update and install infisical
      shell: bash
      run: | 
        sudo apt-get update && sudo apt-get install -y infisical

    - name: Install DeepSource CLI
      run: |
        npm install -g deepsource
        deepsource configure github-action

    - name: Run DeepSource Quality Gate
      env:
        DEEPSOURCE_TOKEN: ${{ secrets.DEEPSOURCE_TOKEN }}
      run: |
        deepsource check
        deepsource_exit_code=$?
        if [ $deepsource_exit_code -ne 0 ]; then
          echo "DeepSource check failed with exit code $deepsource_exit_code."
          exit 1
        fi

    - name: Install dependencies
      run: |
        npm install
       
    - name: Build
      run: |
        infisical run --token ${{secrets.INFISICAL_TOKEN}} --env=prod --path=/ -- npm run generate
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        local-dir: ./dist/
        server-dir: ./public_html/
