name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17'

    - name: Install infisical-cli
      shell: bash
      run: curl -1sLf  'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash

    - name: apt update and install infisical
      shell: bash
      run: | 
        sudo apt-get update && sudo apt-get install -y infisical
      
    - name: Install dependencies
      run: |
        npm install
       
    - name: Build
      run: |
        infisical run --env=prod --path=/ -- npm run generate
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        local-dir: ./dist/
        server-dir: ./public_html/
