name: Deploy to FTP

on: push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17'
    - name: Read a variable
      run: echo "My APP_ID value is ${{ secrets.NUXT_GITHUB_TOKEN }}"
      
    - name: Build
      env:
        CI: false
        NUXT_CONTACT_FORM_API: ${{ secrets.NUXT_CONTACT_FORM_API }}
        NUXT_GITHUB_TOKEN: ${{ secrets.NUXT_GITHUB_TOKEN }}
        GQL_GITHUB_HOST: ${{ secrets.GQL_GITHUB_HOST }}
        NUXT_CALENDLY_URL: ${{ secrets.NUXT_CALENDLY_URL }}
      run: |
        npm install
        npm run generate
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        local-dir: ./dist/
        server-dir: ./public_html/