name: Deploy to FTP

on: push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17'
      
    - name: Build
      env:
        CI: false
      run: |
        npm install
        NUXT_CONTACT_FORM_API=$NUXT_CONTACT_FORM_API NUXT_GITHUB_TOKEN=$NUXT_GITHUB_TOKEN GQL_GITHUB_HOST=$GQL_GITHUB_HOST NUXT_CALENDLY_URL=$NUXT_CALENDLY_URL
        npm run generate
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        local-dir: ./dist/
        server-dir: ./public_html/